version: "3"
services:
  neo4j:
    build:
      dockerfile: ./src/neo4j/Dockerfile
    restart: always
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
    expose:
      - 7474
      - 7687
    ports:
      - 7474:7474
      - 7687:7687
  # Uncomment the following lines to make the database data persistent
  #   volumes:
  # - ./neo4j_data:/data
  reverse_proxy:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: ./src/reverse-proxy/Dockerfile
    ports:
      - 8080:80
  express-api:
    depends_on:
      - neo4j
    restart: always
    build:
      dockerfile: ./src/apps/crawler-server/Dockerfile
    expose:
      - 4000
