version: "3"
services:
  neo4j:
    build:
      dockerfile: ./src/neo4j/Dockerfile
    restart: always
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
    expose:
      - 7474
      - 7687
    # Uncomment the following lines to make the database data persistent
    volumes:
      - neo4j-data:/data
  reverse_proxy:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: ./src/reverse-proxy/Dockerfile
    ports:
      - 8080:80
  express-api:
    depends_on:
      - neo4j
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_HOSTNAME=work-queue
      - RABBITMQ_PORT=5672
      - NEO4J_URL=${NEO4J_URL}
      - CRAWLER_WORKER_COUNT=${CRAWLER_WORKER_COUNT}
    build:
      dockerfile: ./src/apps/crawler-server/Dockerfile
    expose:
      - 4000
  work-queue:
    restart: always
    image: rabbitmq:3-management
    hostname: work-queue
    # data is saved to a volume by default
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    expose:
      - 5672
      - 15672
    ports:
      - 15672:15672 # RabbitMQ monitoring, TODO: pass through nginx

volumes:
  neo4j-data:
