services:
  neo4j:
      image: neo4j:4.0.4
      environment:
        - NEO4J_AUTH=neo4j/password
      expose:
        - 7474
        - 7687
      ports:
        - 7474:7474
        - 7687:7687
    # Uncomment the following lines to make the database data persistent
    #   volumes:
        # - ./neo4j_data:/data
